import Head from "next/head";
import Header from "@/components/Header";
import Featured from "@/components/Featured";
import { Product } from "@/models/ProductSchema";
import { mongooseCoonect } from "@/lib/mongoose";
import NewProducts from "@/components/NewProducts";

export default function Home({ featuredProduct, newProducts }) {
  return (
    <>
      <Head>
        <title>ShopScript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Featured product={featuredProduct} />
      <NewProducts products={newProducts} />
    </>
  );
}

export async function getServerSideProps() {
  const featuredProductId = "6469c3d4a7d4323f5d7d0ba9";
  await mongooseCoonect();
  const featuredProduct = await Product.findById(featuredProductId);
  const newProducts = await Product.find({}, null, {
    sort: { _id: -1 },
    limit: 10,
  });

  return {
    props: {
      featuredProduct: JSON.parse(JSON.stringify(featuredProduct)),
      newProducts: JSON.parse(JSON.stringify(newProducts)),
    },
  };
}
